development: &DEFAULTS
    adapter: postgresql
    encoding: utf8
    reconnect: false
    database: blog_development
    host: localhost
    username: root
    min_messages: WARNING
    template: template0
    port: 5432


production:
  adapter: postgresql
  encoding: utf8
  database: blog_production
  username: blogappadmin
  host: blogapp.cy4y7i7flyo8.us-west-2.rds.amazonaws.com
  password: Begampur83!
  port: 5432
  pool: 5
  timeout: 5000